package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Cleanup9con'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Cleanup9con")) {
    vcs {
        add(DslContext.settingsRoot.id!!)
        add(AbsoluteId("GitJavaEclipse"), "+:java_eclipse/new2_aa => .", "+:java_eclipse/bin => java_eclipse/bin", "+:java_eclipse/src => java_eclipse/src")
    }
}
