package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Cleanup9_Cleanup9con'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Cleanup9_Cleanup9con")) {
    cleanup {
        expect {
            keep {
                id = "KEEP_RULE_118"
                keepAtLeast = builds(5)
                dataToKeep = everything()
                preserveArtifactsDependencies = true
            }
        }
        update {
            keep {
                disabled = true
                id = "KEEP_RULE_118"
                keepAtLeast = builds(5)
                dataToKeep = everything()
                preserveArtifactsDependencies = true
            }
        }
        expect {
            keep {
                id = "KEEP_RULE_130"
                keepAtLeast = allBuilds()
                applyToBuilds {
                    inBranches("""
                        +:*overrie\den
                        +:*overrie\den
                        +:*overrie\den
                        +:*overrie\den
                        +:*overrie\den
                    """.trimIndent())
                    inPersonalBuilds = personal()
                    withStatus = successful()
                }
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = byPattern("""
                        +:cleanup9aconfigoverriden/cleanup9aconfigooverridedn/**.*
                        +:cleanup9aconfigoverriden/cleanup9aconfigoverriden/**.*
                    """.trimIndent())
                }
                applyPerEachBranch()
                preserveArtifactsDependencies = true
            }
        }
        update {
            keep {
                disabled = true
                id = "KEEP_RULE_130"
                keepAtLeast = allBuilds()
                applyToBuilds {
                    inBranches("""
                        +:*overrie\den
                        +:*overrie\den
                        +:*overrie\den
                        +:*overrie\den
                        +:*overrie\den
                    """.trimIndent())
                    inPersonalBuilds = personal()
                    withStatus = successful()
                }
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = byPattern("""
                        +:cleanup9aconfigoverriden/cleanup9aconfigooverridedn/**.*
                        +:cleanup9aconfigoverriden/cleanup9aconfigoverriden/**.*
                    """.trimIndent())
                }
                applyPerEachBranch()
                preserveArtifactsDependencies = true
            }
        }
        add {
            keep {
                disabled = true
                id = "KEEP_RULE_128"
            }
        }
        add {
            keep {
                disabled = true
                id = "KEEP_RULE_129"
            }
        }
    }
}
